# Start from the official RabbitMQ image
FROM rabbitmq:3-management

# Optional: Add any custom configuration files, plugins, or management tools
# COPY custom.conf /etc/rabbitmq/

# Run any custom setup scripts or commands if needed
# RUN rabbitmq-plugins enable rabbitmq_management
